// Copyright (c) VolcanicArts. Licensed under the GPL-3.0 License.
// See the LICENSE file in the repository root for full license text.

namespace VRCOSC.App.Inputs;

using System.Windows.Input;
using SharpHook.Data;

public static class KeyConverter
{
    public static KeyCode ToSharpHook(this Key key) => key switch
    {
        Key.None => KeyCode.VcUndefined,

        Key.Cancel => KeyCode.VcCancel,
        Key.Back => KeyCode.VcBackspace,
        Key.Tab => KeyCode.VcTab,
        Key.Enter or Key.Return => KeyCode.VcEnter,
        Key.Pause => KeyCode.VcPause,
        Key.Capital or Key.CapsLock => KeyCode.VcCapsLock,
        Key.HangulMode or Key.KanaMode => KeyCode.VcKana,
        Key.JunjaMode => KeyCode.VcJunja,
        Key.FinalMode => KeyCode.VcFinal,
        Key.HanjaMode or Key.KanjiMode => KeyCode.VcHanja,
        Key.Escape => KeyCode.VcEscape,
        Key.ImeConvert => KeyCode.VcConvert,
        Key.ImeNonConvert => KeyCode.VcNonConvert,
        Key.ImeAccept => KeyCode.VcAccept,
        Key.ImeModeChange => KeyCode.VcModeChange,
        Key.Space => KeyCode.VcSpace,

        Key.PageUp or Key.Prior => KeyCode.VcPageUp,
        Key.PageDown or Key.Next => KeyCode.VcPageDown,
        Key.End => KeyCode.VcEnd,
        Key.Home => KeyCode.VcHome,

        Key.Left => KeyCode.VcLeft,
        Key.Up => KeyCode.VcUp,
        Key.Right => KeyCode.VcRight,
        Key.Down => KeyCode.VcDown,

        Key.Insert => KeyCode.VcInsert,
        Key.Delete => KeyCode.VcDelete,

        Key.PrintScreen => KeyCode.VcPrintScreen,
        Key.Scroll => KeyCode.VcScrollLock,
        Key.NumLock => KeyCode.VcNumLock,

        Key.LeftShift => KeyCode.VcLeftShift,
        Key.RightShift => KeyCode.VcRightShift,
        Key.LeftCtrl => KeyCode.VcLeftControl,
        Key.RightCtrl => KeyCode.VcRightControl,
        Key.LeftAlt => KeyCode.VcLeftAlt,
        Key.RightAlt => KeyCode.VcRightAlt,
        Key.LWin => KeyCode.VcLeftMeta,
        Key.RWin => KeyCode.VcRightMeta,

        Key.Multiply => KeyCode.VcNumPadMultiply,
        Key.Add => KeyCode.VcNumPadAdd,
        Key.Subtract => KeyCode.VcNumPadSubtract,
        Key.Decimal => KeyCode.VcNumPadDecimal,
        Key.Divide => KeyCode.VcNumPadDivide,

        Key.NumPad0 => KeyCode.VcNumPad0,
        Key.NumPad1 => KeyCode.VcNumPad1,
        Key.NumPad2 => KeyCode.VcNumPad2,
        Key.NumPad3 => KeyCode.VcNumPad3,
        Key.NumPad4 => KeyCode.VcNumPad4,
        Key.NumPad5 => KeyCode.VcNumPad5,
        Key.NumPad6 => KeyCode.VcNumPad6,
        Key.NumPad7 => KeyCode.VcNumPad7,
        Key.NumPad8 => KeyCode.VcNumPad8,
        Key.NumPad9 => KeyCode.VcNumPad9,

        Key.D0 => KeyCode.Vc0,
        Key.D1 => KeyCode.Vc1,
        Key.D2 => KeyCode.Vc2,
        Key.D3 => KeyCode.Vc3,
        Key.D4 => KeyCode.Vc4,
        Key.D5 => KeyCode.Vc5,
        Key.D6 => KeyCode.Vc6,
        Key.D7 => KeyCode.Vc7,
        Key.D8 => KeyCode.Vc8,
        Key.D9 => KeyCode.Vc9,

        Key.A => KeyCode.VcA,
        Key.B => KeyCode.VcB,
        Key.C => KeyCode.VcC,
        Key.D => KeyCode.VcD,
        Key.E => KeyCode.VcE,
        Key.F => KeyCode.VcF,
        Key.G => KeyCode.VcG,
        Key.H => KeyCode.VcH,
        Key.I => KeyCode.VcI,
        Key.J => KeyCode.VcJ,
        Key.K => KeyCode.VcK,
        Key.L => KeyCode.VcL,
        Key.M => KeyCode.VcM,
        Key.N => KeyCode.VcN,
        Key.O => KeyCode.VcO,
        Key.P => KeyCode.VcP,
        Key.Q => KeyCode.VcQ,
        Key.R => KeyCode.VcR,
        Key.S => KeyCode.VcS,
        Key.T => KeyCode.VcT,
        Key.U => KeyCode.VcU,
        Key.V => KeyCode.VcV,
        Key.W => KeyCode.VcW,
        Key.X => KeyCode.VcX,
        Key.Y => KeyCode.VcY,
        Key.Z => KeyCode.VcZ,

        Key.F1 => KeyCode.VcF1,
        Key.F2 => KeyCode.VcF2,
        Key.F3 => KeyCode.VcF3,
        Key.F4 => KeyCode.VcF4,
        Key.F5 => KeyCode.VcF5,
        Key.F6 => KeyCode.VcF6,
        Key.F7 => KeyCode.VcF7,
        Key.F8 => KeyCode.VcF8,
        Key.F9 => KeyCode.VcF9,
        Key.F10 => KeyCode.VcF10,
        Key.F11 => KeyCode.VcF11,
        Key.F12 => KeyCode.VcF12,
        Key.F13 => KeyCode.VcF13,
        Key.F14 => KeyCode.VcF14,
        Key.F15 => KeyCode.VcF15,
        Key.F16 => KeyCode.VcF16,
        Key.F17 => KeyCode.VcF17,
        Key.F18 => KeyCode.VcF18,
        Key.F19 => KeyCode.VcF19,
        Key.F20 => KeyCode.VcF20,
        Key.F21 => KeyCode.VcF21,
        Key.F22 => KeyCode.VcF22,
        Key.F23 => KeyCode.VcF23,
        Key.F24 => KeyCode.VcF24,

        Key.Oem3 => KeyCode.VcBackQuote,
        Key.OemMinus => KeyCode.VcMinus,
        Key.OemPlus => KeyCode.VcEquals,
        Key.OemOpenBrackets => KeyCode.VcOpenBracket,
        Key.Oem6 => KeyCode.VcCloseBracket,
        Key.Oem5 => KeyCode.VcBackslash,
        Key.Oem1 => KeyCode.VcSemicolon,
        Key.Oem7 => KeyCode.VcQuote,
        Key.OemComma => KeyCode.VcComma,
        Key.OemPeriod => KeyCode.VcPeriod,
        Key.OemQuestion => KeyCode.VcSlash,

        Key.Apps => KeyCode.VcContextMenu,
        Key.Sleep => KeyCode.VcSleep,
        Key.Help => KeyCode.VcHelp,
        Key.Clear or Key.OemClear => KeyCode.VcNumPadClear,
        Key.Separator => KeyCode.VcNumPadSeparator,
        Key.OemBackslash => KeyCode.VcSection,
        Key.Oem8 => KeyCode.VcMisc,
        Key.ImeProcessed => KeyCode.VcProcess,

        Key.BrowserBack => KeyCode.VcBrowserBack,
        Key.BrowserForward => KeyCode.VcBrowserForward,
        Key.BrowserRefresh => KeyCode.VcBrowserRefresh,
        Key.BrowserStop => KeyCode.VcBrowserStop,
        Key.BrowserSearch => KeyCode.VcBrowserSearch,
        Key.BrowserFavorites => KeyCode.VcBrowserFavorites,
        Key.BrowserHome => KeyCode.VcBrowserHome,

        Key.VolumeMute => KeyCode.VcVolumeMute,
        Key.VolumeDown => KeyCode.VcVolumeDown,
        Key.VolumeUp => KeyCode.VcVolumeUp,

        Key.MediaNextTrack => KeyCode.VcMediaNext,
        Key.MediaPreviousTrack => KeyCode.VcMediaPrevious,
        Key.MediaStop => KeyCode.VcMediaStop,
        Key.MediaPlayPause => KeyCode.VcMediaPlay,

        Key.LaunchMail => KeyCode.VcAppMail,
        Key.SelectMedia => KeyCode.VcMediaSelect,
        Key.LaunchApplication1 => KeyCode.VcApp1,
        Key.LaunchApplication2 => KeyCode.VcApp2,

        _ => KeyCode.VcUndefined
    };

    public static Key ToWpf(this KeyCode key) => key switch
    {
        KeyCode.VcUndefined => Key.None,

        KeyCode.VcCancel => Key.Cancel,
        KeyCode.VcBackspace => Key.Back,
        KeyCode.VcTab => Key.Tab,
        KeyCode.VcEnter => Key.Enter,
        KeyCode.VcCapsLock => Key.CapsLock,
        KeyCode.VcKana => Key.KanaMode,
        KeyCode.VcJunja => Key.JunjaMode,
        KeyCode.VcFinal => Key.FinalMode,
        KeyCode.VcHanja => Key.HanjaMode,
        KeyCode.VcEscape => Key.Escape,
        KeyCode.VcConvert => Key.ImeConvert,
        KeyCode.VcNonConvert => Key.ImeNonConvert,
        KeyCode.VcAccept => Key.ImeAccept,
        KeyCode.VcModeChange => Key.ImeModeChange,
        KeyCode.VcSpace => Key.Space,

        KeyCode.VcPageUp => Key.PageUp,
        KeyCode.VcPageDown => Key.PageDown,
        KeyCode.VcEnd => Key.End,
        KeyCode.VcHome => Key.Home,

        KeyCode.VcLeft => Key.Left,
        KeyCode.VcUp => Key.Up,
        KeyCode.VcRight => Key.Right,
        KeyCode.VcDown => Key.Down,

        KeyCode.VcInsert => Key.Insert,
        KeyCode.VcDelete => Key.Delete,

        KeyCode.VcPrintScreen => Key.PrintScreen,
        KeyCode.VcScrollLock => Key.Scroll,
        KeyCode.VcNumLock => Key.NumLock,

        KeyCode.VcLeftShift => Key.LeftShift,
        KeyCode.VcRightShift => Key.RightShift,
        KeyCode.VcLeftControl => Key.LeftCtrl,
        KeyCode.VcRightControl => Key.RightCtrl,
        KeyCode.VcLeftAlt => Key.LeftAlt,
        KeyCode.VcRightAlt => Key.RightAlt,
        KeyCode.VcLeftMeta => Key.LWin,
        KeyCode.VcRightMeta => Key.RWin,

        KeyCode.VcNumPad0 => Key.NumPad0,
        KeyCode.VcNumPad1 => Key.NumPad1,
        KeyCode.VcNumPad2 => Key.NumPad2,
        KeyCode.VcNumPad3 => Key.NumPad3,
        KeyCode.VcNumPad4 => Key.NumPad4,
        KeyCode.VcNumPad5 => Key.NumPad5,
        KeyCode.VcNumPad6 => Key.NumPad6,
        KeyCode.VcNumPad7 => Key.NumPad7,
        KeyCode.VcNumPad8 => Key.NumPad8,
        KeyCode.VcNumPad9 => Key.NumPad9,

        KeyCode.VcNumPadMultiply => Key.Multiply,
        KeyCode.VcNumPadAdd => Key.Add,
        KeyCode.VcNumPadSubtract => Key.Subtract,
        KeyCode.VcNumPadDecimal => Key.Decimal,
        KeyCode.VcNumPadDivide => Key.Divide,

        KeyCode.Vc0 => Key.D0,
        KeyCode.Vc1 => Key.D1,
        KeyCode.Vc2 => Key.D2,
        KeyCode.Vc3 => Key.D3,
        KeyCode.Vc4 => Key.D4,
        KeyCode.Vc5 => Key.D5,
        KeyCode.Vc6 => Key.D6,
        KeyCode.Vc7 => Key.D7,
        KeyCode.Vc8 => Key.D8,
        KeyCode.Vc9 => Key.D9,

        KeyCode.VcA => Key.A,
        KeyCode.VcB => Key.B,
        KeyCode.VcC => Key.C,
        KeyCode.VcD => Key.D,
        KeyCode.VcE => Key.E,
        KeyCode.VcF => Key.F,
        KeyCode.VcG => Key.G,
        KeyCode.VcH => Key.H,
        KeyCode.VcI => Key.I,
        KeyCode.VcJ => Key.J,
        KeyCode.VcK => Key.K,
        KeyCode.VcL => Key.L,
        KeyCode.VcM => Key.M,
        KeyCode.VcN => Key.N,
        KeyCode.VcO => Key.O,
        KeyCode.VcP => Key.P,
        KeyCode.VcQ => Key.Q,
        KeyCode.VcR => Key.R,
        KeyCode.VcS => Key.S,
        KeyCode.VcT => Key.T,
        KeyCode.VcU => Key.U,
        KeyCode.VcV => Key.V,
        KeyCode.VcW => Key.W,
        KeyCode.VcX => Key.X,
        KeyCode.VcY => Key.Y,
        KeyCode.VcZ => Key.Z,

        KeyCode.VcF1 => Key.F1,
        KeyCode.VcF2 => Key.F2,
        KeyCode.VcF3 => Key.F3,
        KeyCode.VcF4 => Key.F4,
        KeyCode.VcF5 => Key.F5,
        KeyCode.VcF6 => Key.F6,
        KeyCode.VcF7 => Key.F7,
        KeyCode.VcF8 => Key.F8,
        KeyCode.VcF9 => Key.F9,
        KeyCode.VcF10 => Key.F10,
        KeyCode.VcF11 => Key.F11,
        KeyCode.VcF12 => Key.F12,
        KeyCode.VcF13 => Key.F13,
        KeyCode.VcF14 => Key.F14,
        KeyCode.VcF15 => Key.F15,
        KeyCode.VcF16 => Key.F16,
        KeyCode.VcF17 => Key.F17,
        KeyCode.VcF18 => Key.F18,
        KeyCode.VcF19 => Key.F19,
        KeyCode.VcF20 => Key.F20,
        KeyCode.VcF21 => Key.F21,
        KeyCode.VcF22 => Key.F22,
        KeyCode.VcF23 => Key.F23,
        KeyCode.VcF24 => Key.F24,

        KeyCode.VcBackQuote => Key.Oem3,
        KeyCode.VcMinus => Key.OemMinus,
        KeyCode.VcEquals => Key.OemPlus,
        KeyCode.VcOpenBracket => Key.OemOpenBrackets,
        KeyCode.VcCloseBracket => Key.Oem6,
        KeyCode.VcBackslash => Key.Oem5,
        KeyCode.VcSemicolon => Key.Oem1,
        KeyCode.VcQuote => Key.Oem7,
        KeyCode.VcComma => Key.OemComma,
        KeyCode.VcPeriod => Key.OemPeriod,
        KeyCode.VcSlash => Key.OemQuestion,

        KeyCode.VcContextMenu => Key.Apps,
        KeyCode.VcSleep => Key.Sleep,
        KeyCode.VcHelp => Key.Help,
        KeyCode.VcNumPadClear => Key.Clear,
        KeyCode.VcNumPadSeparator => Key.Separator,
        KeyCode.VcSection => Key.OemBackslash,
        KeyCode.VcMisc => Key.Oem8,
        KeyCode.VcProcess => Key.ImeProcessed,
        KeyCode.VcNumPadEnter => Key.Enter, // WPF doesn't distinguish numpad Enter

        KeyCode.VcBrowserBack => Key.BrowserBack,
        KeyCode.VcBrowserForward => Key.BrowserForward,
        KeyCode.VcBrowserRefresh => Key.BrowserRefresh,
        KeyCode.VcBrowserStop => Key.BrowserStop,
        KeyCode.VcBrowserSearch => Key.BrowserSearch,
        KeyCode.VcBrowserFavorites => Key.BrowserFavorites,
        KeyCode.VcBrowserHome => Key.BrowserHome,

        KeyCode.VcVolumeMute => Key.VolumeMute,
        KeyCode.VcVolumeDown => Key.VolumeDown,
        KeyCode.VcVolumeUp => Key.VolumeUp,

        KeyCode.VcMediaNext => Key.MediaNextTrack,
        KeyCode.VcMediaPrevious => Key.MediaPreviousTrack,
        KeyCode.VcMediaStop => Key.MediaStop,
        KeyCode.VcMediaPlay => Key.MediaPlayPause,

        KeyCode.VcAppMail => Key.LaunchMail,
        KeyCode.VcMediaSelect => Key.SelectMedia,
        KeyCode.VcApp1 => Key.LaunchApplication1,
        KeyCode.VcApp2 => Key.LaunchApplication2,

        _ => Key.None
    };
}