<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <WindowsSdkPackageVersion>10.0.26100.56</WindowsSdkPackageVersion>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <LangVersion>latestmajor</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CsWin32Generate>true</CsWin32Generate>
        <Version>$(GlobalVersion)</Version>
        <AssemblyVersion>$(GlobalVersion)</AssemblyVersion>
        <FileVersion>$(GlobalVersion)</FileVersion>
        <AssemblyName>VRCOSC.App</AssemblyName>
        <PackageId>VolcanicArts.VRCOSC.SDK</PackageId>
        <Title>VRCOSC's SDK</Title>
        <Authors>VolcanicArts</Authors>
        <Description>VRCOSC's SDK for developing VRCOSC modules</Description>
        <PackageProjectUrl>https://github.com/VolcanicArts/VRCOSC</PackageProjectUrl>
        <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/VolcanicArts/VRCOSC</RepositoryUrl>
        <Company>VRCOSC</Company>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommandLineParser" Version="2.9.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Extended.Wpf.Toolkit" Version="5.1.2" />
        <PackageReference Include="Fastenshtein" Version="1.0.12" />
        <PackageReference Include="FontAwesome6.Fonts" Version="2.5.1" />
        <PackageReference Include="JsonPath.Net" Version="3.0.2" />
        <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.7-pre733" />
        <PackageReference Include="MathParser.org-mXparser" Version="6.1.1" />
        <PackageReference Include="MeaMod.DNS" Version="1.0.71" />
        <PackageReference Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
        <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.333">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.158" />
        <PackageReference Include="NAudio" Version="2.3.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Octokit" Version="14.0.0" />
        <PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2.3" />
        <PackageReference Include="PresentMonFps" Version="2.0.6" />
        <PackageReference Include="SDL3-CS" Version="3.4.16" />
        <PackageReference Include="SDL3-CS.Windows" Version="3.4.16" />
        <PackageReference Include="Semver" Version="3.0.0" />
        <PackageReference Include="SharpHook" Version="8.0.0" />
        <PackageReference Include="SoundFlow" Version="1.4.1" />
        <PackageReference Include="TwitchLib.Api" Version="3.11.0-preview.218.c76ee84" />
        <PackageReference Include="TwitchLib.Api.Core" Version="3.11.0-preview.218.c76ee84" />
        <PackageReference Include="TwitchLib.Api.Core.Enums" Version="3.11.0-preview.218.c76ee84" />
        <PackageReference Include="TwitchLib.Api.Core.Interfaces" Version="3.11.0-preview.218.c76ee84" />
        <PackageReference Include="TwitchLib.Api.Core.Models" Version="3.11.0-preview.218.c76ee84" />
        <PackageReference Include="TwitchLib.Api.Helix" Version="3.11.0-preview.218.c76ee84" />
        <PackageReference Include="TwitchLib.Api.Helix.Models" Version="3.11.0-preview.218.c76ee84" />
        <PackageReference Include="TwitchLib.EventSub.Core" Version="3.1.0-preview.81.5919dce" />
        <PackageReference Include="TwitchLib.EventSub.Websockets" Version="0.9.0-preview.91.e7a2a33" />
        <PackageReference Include="Velopack" Version="1.2.0" />
        <PackageReference Include="VolcanicArts.FastOSC" Version="2.0.0" />
        <PackageReference Include="VolcanicArts.Libs.OpenVR" Version="2.5.1" />
        <PackageReference Include="Whisper.net" Version="1.9.1" />
        <PackageReference Include="Whisper.net.Runtime" Version="1.9.1" />
        <PackageReference Include="Whisper.net.Runtime.Vulkan" Version="1.9.1" />
        <PackageReference Include="WindowsInput" Version="6.4.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\OpenVR\action_manifest.json" />
      <EmbeddedResource Include="Resources\OpenVR\action_manifest.json" />
      <None Remove="Resources\OpenVR\knuckles_bindings.json" />
      <EmbeddedResource Include="Resources\OpenVR\knuckles_bindings.json" />
      <None Remove="Resources\OpenVR\oculus_touch_bindings.json" />
      <EmbeddedResource Include="Resources\OpenVR\oculus_touch_bindings.json" />
      <None Remove="Resources\OpenVR\SteamImage.png" />
      <EmbeddedResource Include="Resources\OpenVR\SteamImage.png" />
      <None Remove="Resources\OpenVR\vive_bindings.json" />
      <EmbeddedResource Include="Resources\OpenVR\vive_bindings.json" />
      <None Remove="Resources\OpenVR\holographic_controller_bindings.json" />
      <EmbeddedResource Include="Resources\OpenVR\holographic_controller_bindings.json" />
      <None Remove="Resources\OpenVR\vd_hand_controller_bindings.json" />
      <EmbeddedResource Include="Resources\OpenVR\vd_hand_controller_bindings.json" />
      <None Remove="Resources\OpenVR\vive_cosmos_controller_bindings.json" />
      <EmbeddedResource Include="Resources\OpenVR\vive_cosmos_controller_bindings.json" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="UI\Views\Packages\PackagesView.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
      <Page Update="UI\Views\Modules\ModulesView.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
      <Page Update="UI\Views\Run\Tabs\AvatarParameterTabView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Run\Tabs\ChatBoxTabView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Run\Tabs\RuntimeTabView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Windows\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Styles\IconButtonStyle.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Styles\TextBoxStyle.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Styles\VRCOSCButtonStyle.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Styles\VRCOSCCheckBoxStyle.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Themes\Dark.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Themes\Light.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Windows\Modules\ModulePrefabsWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Windows\Modules\ModuleSettingsWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Modules\Settings\DateTimeSettingView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Modules\Settings\EnumDropdownSettingView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Modules\Settings\ListTextBoxSettingView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Modules\Settings\MutableKeyValuePairListSettingView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Modules\Settings\SliderSettingView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Modules\Settings\TextBoxSettingView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Modules\Settings\ToggleSettingView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Windows\Profiles\ProfileEditWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Windows\ChatBox\ChatBoxClipEditWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\ChatBox\Variables\DropdownVariableOptionView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\ChatBox\Variables\TextBoxVariableOptionView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\ChatBox\Variables\ToggleVariableOptionView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Windows\ChatBox\ChatBoxPreviewWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Core\ChatBoxTextBox.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Windows\ChatBox\ClipVariableEditWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Windows\Modules\ModuleParametersWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Settings\SettingsView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Modules\Settings\PasswordTextBoxSettingView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\Modules\Settings\QueryableParameter\QueryableParameterListModuleSettingView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\AppSettings\AppDebugView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\AppSettings\RouterView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="UI\Views\AppSettings\StartupView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\Fonts\Iosevka-Regular.ttf" />
      <None Remove="Resources\Fonts\Iosevka-SemiBold.ttf" />
      <None Remove="Resources\Fonts\Iosevka-Bold.ttf" />
      <None Remove="Resources\Fonts\Iosevka-BoldItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-BoldOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-Extended.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedBold.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedBoldItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedBoldOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedExtraBold.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedExtraBoldItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedExtraBoldOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedExtraLight.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedExtraLightItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedExtraLightOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedHeavy.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedHeavyItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedHeavyOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedLight.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedLightItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedLightOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedMedium.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedMediumItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedMediumOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedSemiBold.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedSemiBoldItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedSemiBoldOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedThin.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedThinItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtendedThinOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtraBold.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtraBoldItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtraBoldOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtraLight.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtraLightItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ExtraLightOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-Heavy.ttf" />
      <None Remove="Resources\Fonts\Iosevka-HeavyItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-HeavyOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-Italic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-Light.ttf" />
      <None Remove="Resources\Fonts\Iosevka-LightItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-LightOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-Medium.ttf" />
      <None Remove="Resources\Fonts\Iosevka-MediumItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-MediumOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-Oblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-SemiBoldItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-SemiBoldOblique.ttf" />
      <None Remove="Resources\Fonts\Iosevka-Thin.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ThinItalic.ttf" />
      <None Remove="Resources\Fonts\Iosevka-ThinOblique.ttf" />
    </ItemGroup>

</Project>